###############################################################
#                   Authelia configuration                    #
###############################################################
 
host: 0.0.0.0
port: 9091
log_level: info
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: vjK5DgHLrj1DIxMxl7YX5NNr5pRAA  # get secret from here https://www.grc.com/passwords.htm
default_redirection_url: https://auth.example.com
totp:
  issuer: authelia.com
  period: 30
  skew: 1
 
#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl
 
authentication_backend:
  file:
    path: /config/users_database.yml
#    password:
#      algorithm: argon2id
#      iterations: 1
#      key_length: 32
#      salt_length: 16
#      memory: 1024
#      parallelism: 8
 
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: 
        - "jellyfin.example.com"
        - "auth.example.com"
      policy: bypass
    - domain:
        - "*.example.com"
        - "example.com"
      policy: one_factor
#      networks:
#       - 192.168.1.0/24
 
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: LvFBxCP8QHsPVQmJbxuUBzGy9ofrzrOm2zhMXD # get secret from here https://www.grc.com/passwords.htm
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: example.com # Should match whatever your root protected domain is
 
  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
#    password: authelia
 
regulation:
  max_retries: 3
  find_time: 1200
  ban_time: 36000
 
storage:
  local:
    path: /config/db.sqlite3
 
notifier:
  filesystem:
    filename: /config/notification.txt
#  smtp:
#    username: test
#    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
#    password: password
#    host: mail.example.com
#    port: 25
#    sender: admin@example.com